### ISSUE TITLE
Teams presence for US gov cloud

### ISSUE THREAD

**Issue by BobLoblaw06** [a1comms/chromeos-apps-for-office365#1]
Teams for the US gov cloud uses a different domain. The code still works after making a few changes.

I updated the manifest to include the domain.
    "host_permissions": [
        "https://*.teams.microsoft.com/*",
        "https://*.teams.microsoft.com.mcas.ms/*",
        "https://*.teams.live.com/*",
        "https://*.teams.microsoft.us/*"
    ]

changes to background.js
replaced https://teams.microsoft.com/ with https://gov.teams.microsoft.us/
replaced https://presence.teams.microsoft.com/ with https://presence.gov.teams.microsoft.us/

Obviously this makes the extension only function for the US gov cloud. If I get some free time I will see if I can get it to continue to work for both.
Thanks for writing this up. It's been a thorn in my side for way too long.

**Comment by iamacarpet** [comment]
I'm just pushing the committed update to the Chrome Web Store - hopefully it'll be available soon.
