### ISSUE TITLE
https://teams.microsoft.com/v2/

### ISSUE THREAD

**Issue by jise** [a1comms/chromeos-apps-for-office365#2]
Thank you very much for your tip on how to install Teams as a PWA in ChromeOS. I had no idea it was a PWA until now, since it didn't automatically install for ChromeOS, I had to install Teams via the Create shortcut, but even though I had the Teams app installed this way, your ["MS Teams Shelf/Dock Badge Notification"](https://chrome.google.com/webstore/detail/badge-notifications-for-m/opcgcmanfocenaiippbgachholecmakm) add-on worked for me reliably.

Coincidentally, yesterday in our work tenant, the Teams app offered me the option to switch to the new version https://teams.microsoft.com/v2/:
![Screenshot 2023-11-02 14 07 37](https://github.com/a1comms/chromeos-apps-for-office365/assets/6588902/b0c334a9-f51a-461f-9fed-eb5532bf24a6)

But then your ["Badge Notifications for MS Teams PWA"](https://chrome.google.com/webstore/detail/badge-notifications-for-m/opcgcmanfocenaiippbgachholecmakm) add-on stopped working. Will it have to be adapted for the new version?

I got the new URL from the New Teams PWA as follows:
![Screenshot 2023-11-02 14 03 59](https://github.com/a1comms/chromeos-apps-for-office365/assets/6588902/502eaea2-055d-4c50-a9ff-1c7c6751d733)

**Comment by iamacarpet** [comment]
Thanks @jise ,

I finally got access to Teams v2 on the web today, even though our tenant has it set as preferred since the day you opened the ticket :).

You'll see I've pushed the required fixes, and I'm submitting to the Chrome Web Store today, waiting on Google's approval before they are published.
