### ISSUE TITLE
Teams presence for US gov Part 2

### ISSUE THREAD

**Issue by ArrowNought** [a1comms/chromeos-apps-for-office365#3]
There's another format of URL that my part of the gov uses:

https://dod.teams.microsoft.us.mcas-gov.us/

**Comment by iamacarpet** [comment]
Sorry about the delay @ArrowNought , it's been a busy few weeks!

That should be done - just pending review from Google before it's published.

**Comment by iamacarpet** [comment]
Just got an email to say they've reviewed & published it already :)
